// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"time"
)

type User struct {
	ID        string
	Name      string
	Email     string
	CreatedAt time.Time
}
